---
# title: "Tesis de Licenciatura"
author: "Paola Corrales"
date: ''
output:
  pdf_document:
    keep_tex: yes
    latex_engine: xelatex
    number_sections: yes
    # toc: yes
    # toc_depth: 4
  word_document:
    reference_docx: word-template.docx
    # toc: yes
    # toc_depth: '4'
classoption: oneside, a4paper
documentclass: book
fontsize: 12pt
geometry: inner = 3cm, outer = 2cm, top = 2.5cm, bottom = 2.5cm
header-includes:
- \usepackage{setspace}
- \setstretch{1.5}
- \usepackage{subfig}
lang: es-AR
link-citation: yes
csl: Bibliografia/meteorologica.csl
subtitle: Validación de parametrizaciones de capa límite utilizando datos de radar
bibliography:
- Bibliografia/papers.bib
- Bibliografia/packages.bib
nocite: |
  @Amante2009, @Kalnay1996
---


```{r setup, include=FALSE, cache = FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      cache = TRUE,
                      warning = FALSE,
                      message = FALSE)

knitr::write_bib(c("base", "data.table", "ggplot2", "metR"),
                 file = "Bibliografia/packages.bib")
# librerías
library(metR)
library(ggplot2)
library(ggforce)
library(ggrepel)
library(lubridate)
library(magrittr)
library(dplyr)
library(dtplyr)
library(viridis)
library(directlabels)
library(data.table)
library(ncdf4)
library(knitr)
library(kableExtra)
library(circular)
source("helpfun.R")

# Variables útiles
mapa.ar <- setDT(fortify(rnaturalearth::ne_states(country = c("Argentina"))))
map2 <- setDT(fortify(rnaturalearth::ne_countries(country = c("Brazil", "Uruguay"))))
mapa.ar <- rbind(mapa.ar, map2) %>%
   .[, .(long = approx(.I, long, n = .N*5)$y,
         lat = approx(.I, lat, n = .N*5)$y),
     by = .(group)] %>%
   .[, rango := rrange(long, lat)] %>%
   .[, azimut := azimuth(long, lat)] %>%
   .[, group2 := cuad_split(azimut), by = group]

setnames(mapa.ar, "long", "lon")

mapa.sa <- setDT(fortify(rnaturalearth::ne_countries(continent = c("South America", "North America"))))
setnames(mapa.sa, "long", "lon")

mapa.rios <- setDT(fortify(rnaturalearth::ne_load(scale = 10, type = 'rivers_lake_centerlines', category = 'physical', destdir = "seudocache/")))
setnames(mapa.rios, "long", "lon")


text.height <- (297 - 50)/25.4
text.width <- (210 - 50)/25.4

color_manual <- c("#231151", "#d3436e", "#feba80")

path1 <- "~/Dropbox/Tesis/tesis-VAD/Tesis/"
path2 <- "/mnt/Data/VAD/"
remove(map2)
```



```{r leo-vad}

superficie <- setDT(read.sup(paste0(path1, "seudocache/superficie.csv")))
sup_vad <- convert.sup(superficie)

# Caso 1 - 14/01/2016
vad_20160114 <- read.vad(paste0(path2, "20160114/v*"))  
vad_20160114 <- rbind(subset(sup_vad,
                             day(date_time) %in% c(13,14)), vad_20160114)
vad_20160114[, caso := "Caso 1"]

# Caso 3 - 23/01/2016
# vad_20160123 <- read.vad(paste0(path2, "20160123/v*"))  
# vad_20160123 <- rbind(subset(sup_vad,
#                              day(date_time) %in% c(22,23)), vad_20160123)
# vad_20160123[, caso := "Caso 2"]

remove(sup_vad)
```


```{r campo-caso1, fig.cap="Intensidad (m/s) y dirección del viento (grados) correspondiente al Caso 1 (14/01/2016) estimados a partir de las observaciones de radar utilizando la técnica VAD. En el caso de la magnitud del viento se muestran los errores calculados ($dispersi\\acute{o}n$ en círculos y $rmse$ en cruces) cuando superan los 0.5 m/s. \\label{campo-caso1}", fig.subcap=c("Magnitud del viento. \\label{caso1-spd}", "Dirección. \\label{caso1-dir}"), fig.width=0.95*text.width, fig.height=0.4*text.height, fig.ncol=1}

vad_20160114[ht > 0.02] %>%
  ggplot(aes(date_time, ht)) +
  geom_contour(aes(z = spd_smooth, color = ..level..), binwidth = 1) +
  scale_color_viridis(name = "Magnitud\ndel viento", direction = 1,
                      breaks = seq(0, 16, 2), limits = c(0, 16),
                      guide = guide_colorbar(order = 1)) +
  geom_point(data = subset(vad_20160114, rmse1 > 0.5),
             aes(size = rmse1),
             shape = 1, color = "grey25") +
  geom_point(data = subset(vad_20160114, rmse2 > 0.5),
             aes(size = rmse2),
             shape = 4, color = "grey25") +
  geom_label_contour2(aes(z = spd_smooth, label = ..level.., color = ..level..),
                    size = 4,
                    breaks = seq(0, 16, 1)) +
  scale_size(name = "Error", guide = guide_legend(order = 2)) +
  scale_x_datetime(name = "Hora (UTC)",
                   date_breaks = "3 hour",
                   date_labels = "%H:%M",
                   limits = c(as_datetime("2016-01-13 00:00:00"), NA),
                   expand = c(0,0)) +
  scale_y_continuous(name = "Altura (km)", limits = c(0,NA),
                     expand = c(0,0)) +
  theme_minimal()

vad_20160114[minute(date_time) == 0 & !is.na(spd_smooth) & ht < 3] %>%
  ggplot(aes(date_time, ht)) +
  geom_arrow(aes(mag = spd_smooth, angle = di, color = spd_smooth),
             preserve.dir = TRUE) +
  scale_mag(length = 1) +
  # geom_point(data = subset(vad_20160114, rmse1 > 0.5),) + 
  #            aes(size = rmse1),
  #            shape = 1, color = "grey25") +
  # geom_point(data = subset(vad_20160114, rmse2 > 0.5),
  #            aes(size = rmse2),
  #            shape = 4, color = "grey25") +
  scale_color_viridis(name = "Magnitud\ndel viento",
                      breaks = seq(0, 16, 2), limits = c(0, 16)) +
  scale_size_continuous(range = c(0, 5), guide = "none") +
  scale_y_continuous(name = "Altura (km)", limits = c(0,3)) +
  scale_x_datetime(name = "Hora (UTC)",
                   date_breaks = "3 hour",
                   date_labels = "%H",
                   limits = c(as_datetime("2016-01-13 00:00:00"), NA)) +
  theme_minimal()
```


```{r perfiles, fig.cap="Perfil vertical de viento (m/s) estimado a partir de los datos de radar a las 06 y las 17 UTC y el $rmse$ (m/s) en cada punto (sombreado) para los tres casos. Las marcas en los ejes indican la magnitud del viento máxima y mínima (por encima del LLJ) y la altura a la que ocurren. Los valores en superficie fueron obtenidos a partir de los datos del la estación meteorológica Paraná Aero. \\label{perfiles-horarios}", fig.width=0.95*text.width, fig.align='center'}

gdata <- vad_20160114%>%
  .[minute(date_time) == 00 & hour(date_time) %in% c(06, 17) & ht < 2.5 &
      !is.na(spd_smooth)]
ggplot(gdata, aes(ht, spd_smooth, color = as.factor(hour(date_time)))) +
  geom_line() +
  geom_rug(data = gdata[minute(date_time) == 00 & hour(date_time) == 6][, maxspd := max(spd_smooth, na.rm = T), by = caso][spd_smooth == maxspd]) +
  geom_rug(data = gdata[minute(date_time) == 00 & hour(date_time) == 6 & ht > 0.5][, minspd := min(spd_smooth, na.rm = T), by = caso][spd_smooth == minspd]) +
  geom_ribbon(aes(ymin = spd_smooth - rmse2, ymax = spd_smooth + rmse2,
              fill = as.factor(hour(date_time))),
              alpha = 0.5, color = NA) +
  coord_flip() +
  scale_color_manual(name="Hora UTC", values = color_manual) +
  scale_fill_manual(name="Hora UTC", values = color_manual) +
  scale_y_continuous(name = "V (m/s)") +
  scale_x_continuous(name = "Altura (km)", breaks = seq(0, 2.5, 0.5),
                     limits = c(0, 2.5)) +
  facet_wrap(~caso+day(date_time)) +
  theme_minimal()
```


```{r hodografa-horaria, fig.cap="Hodógrafa en función de la altura entre 100 y 3000 metros, para cada caso de estudio observada por el radar a las 06 UTC. El triángulo marca el nivel inferior y los círculos grandes se ubican cada 500 metros. \\label{hodografa-h}", fig.align='center', fig.width=0.75*text.width}

gdata <- vad_20160114 %>%
  .[, hora := hour(date_time)] %>%
  .[, day := day(date_time)] %>% 
  .[minute(date_time) == 00 & hour(date_time) %in% c(06) &
      !is.na(spd_smooth) & ht > 0.02 & ht <= 3]
ggplot(gdata, aes(u, v,  color = caso)) +
  geom_hline(yintercept = 0, color = "darkgrey") +
  geom_vline(xintercept = 0, color = "darkgrey") +
  geom_point(data=subset(gdata, ht != 0.1), size = 1) +
  geom_point(aes(x = ifelse(ht %in% seq(0.1, 3.0, 0.5), u, NA)),
             size = 2) +
  geom_point(data=subset(gdata, ht == 0.1), shape = 17, size = 3) +
  geom_path() +
  scale_color_viridis(name="Casos", discrete = T) +
  scale_x_continuous(name = "u (m/s)") +
  scale_y_continuous(name = "v (m/s)") +
  facet_wrap(~day, scales = "free") +
  #coord_equal() +
  theme_minimal()
```
### Características de la capa límite planetaria

#### Oscilación inercial y LLJ



```{r hodografa-nivel, fig.cap="Hodógrafa temporal para el nivel correspondiente a los datos de la estación meteorológica (a) y 0.3 y 1 km a partir de la estimación del viento con los dato del radar (b). el cuadrado marca el primer tiempo (00 UTC) y cada círculo representa un valor horario (con circulos más grandes cada 6 horas). \\label{hodografa-n}", fig.subcap=c("Datos observados en la estación meteorológica. \\label{hodo-nivel1}", "Datos observados por el radar. \\label{hodo-nivel2}"), fig.width=0.95*text.width, fig.ncol=1, fig.align='center', fig.height=0.25*text.height}

gdata <- vad_20160114
gdata <- as.data.table(gdata) %>%
  .[, hora := hour(date_time)] %>%
  .[, day := day(date_time)] %>% 
  .[ht %in% c(0.01) & !is.na(spd_smooth) &
      minute(date_time) == 00 & hora < 18]
ggplot(gdata, aes(u, v,  color = as.factor(ht))) +
  geom_hline(yintercept = 0, color = "darkgrey") +
  geom_vline(xintercept = 0, color = "darkgrey") +
  geom_point(aes(x = ifelse(hour(date_time) != 0, u, NA)), size = 1) +
  geom_point(aes(x = ifelse(hour(date_time) %in% c(0,6,12), u, NA)),
             size = 2) +
  geom_point(aes(x = ifelse(hour(date_time) == 0, u, NA)), shape = 15,
             size = 3) +
  geom_path() +
  geom_text_repel(aes(label = JumpBy(hora, 6, fill = NA)),
                  data = gdata[ht != 1]) +
  scale_color_manual(name="Altura", values = c("#231151", "#d3436e", "#feba80")) +
  scale_x_continuous(name = "u (m/s)") +
  scale_y_continuous(name = "v (m/s)") +
  coord_equal() +
  facet_wrap(~caso+day) +
  theme_minimal()

gdata <- as.data.table(rbind(vad_20160114)) %>%
  .[, hora := hour(date_time)] %>%
  .[, day := day(date_time)] %>% 
  .[ht %in% c(0.3, 1) & !is.na(spd_smooth) &
      minute(date_time) == 00 & hora <= 18]
ggplot(gdata, aes(u, v,  color = as.factor(ht))) +
  geom_hline(yintercept = 0, color = "darkgrey") +
  geom_vline(xintercept = 0, color = "darkgrey") +
  geom_point(aes(x = ifelse(hour(date_time) != 0, u, NA)), size = 1) +
  geom_point(aes(x = ifelse(hour(date_time) %in% c(0,6,12), u, NA)),
             size = 2) +
  geom_point(aes(x = ifelse(hour(date_time) == 0, u, NA)), shape = 15,
             size = 3) +
  geom_path() +
  geom_text_repel(aes(label = JumpBy(hora, 6, fill = NA)),
                  data = gdata[ht != 1]) +
  scale_color_manual(name="Altura", values = c("#d3436e", "#feba80")) +
  scale_x_continuous(name = "u (m/s)") +
  scale_y_continuous(name = "v (m/s)") +
  coord_equal() +
  facet_wrap(~caso+day) +
  theme_minimal()

```


#### Altura de la capa límite y turbulencia

```{r read-dbz}
files <- Sys.glob(paste0(path2, "caso1_YSU_l/wrf_to_radar/*.nc"))
dbz_20160114 <- rbindlist(lapply(files, read.radar))

# files <- Sys.glob("~/Radar/VAD/PARANA/20160123/240/*.nc")
# dbz_20160123 <- rbindlist(lapply(files, read.radar))
```



```{r dbz, fig.cap="Reflecttividad (dBZ) medida por el radar en función de la altura y el tiempo para el Caso 1 (a), el Caso 2 (b) y el Caso 3 (c). \\label{dbz}", fig.subcap=c("Caso 1. \\label{reflec-1}", "Caso2. \\label{reflec-2}", "Caso 3. \\label{reflec-3}"), fig.align='center', fig.height=0.28*text.height, fig.ncol=1}
elev <- unique(dbz_20160114$elevacion)
dbz_20160114[elevacion == elev[8] & ht_reg > 100] %>%
  ggplot(aes(date, ht_reg/1000)) +
  #geom_line(aes(color = factor(elevacion))) +
  geom_tile(aes(fill = dbz, color = dbz)) +
  scale_fill_viridis(name = "dBZ",
               limits = c(NA, NA)) +
  scale_color_viridis(name = "dBZ",
                    limits = c(NA, NA)) +
  # geom_contour(data = vad_20160114[ht > 0.02], aes(date_time, ht, z = spd_smooth)) +
  scale_y_continuous(name = "Altura (km)",
                     limits = c(0, 3),
                     breaks = seq(0, 3, 0.5),
                     expand = c(0,0)) +
  scale_x_datetime(name = NULL,
                   date_breaks = "3 hour",
                   date_labels = "%H:%M",
                   limits = c(as_datetime("2016-01-13 00:00:00"), NA),
                   expand = c(0,0)) +
  theme_minimal()


# dbz_20160123[elevacion == elev[8] & ht_reg > 200] %>%
#   ggplot(aes(date, ht_reg/1000)) +
#   #geom_line(aes(color = factor(elevacion))) +
#   geom_tile(aes(fill = dbz, color = dbz)) +
#   scale_fill_viridis(name = "dBZ",
#                limits = c(NA, NA)) +
#   scale_color_viridis(name = "dBZ",
#                     limits = c(NA, NA)) +
#   scale_y_continuous(name = "Altura (km)",
#                      limits = c(0, 3),
#                      breaks = seq(0, 3, 0.5),
#                      expand = c(0,0)) +
#   scale_x_datetime(name = "Hora (UTC)",
#                    date_breaks = "3 hour",
#                    date_labels = "%H:%M",
#                    limits = c(as_datetime("2016-01-23 00:00:00"), NA),
#                    expand = c(0,0)) +
#   theme_minimal()

```

```{r pblh-dbz, fig.cap="Valor absoluto del gradiente vertical de reflectividad (dBZ/m) en función de la altura y el tiempo para el Caso 1 (a), el Caso 2 (b) y el Caso 3 (c). \\label{pblh-dbz}", fig.subcap=c("Caso 1. \\label{dbz-1}", "Caso2. \\label{dbz-2}", "Caso 3. \\label{dbz-3}"), fig.align='center', fig.height=0.28*text.height, fig.ncol=1}
elev <- unique(dbz_20160114$elevacion)
dbz_20160114[elevacion == elev[8] & ht_reg > 200] %>%
  ggplot(aes(date, ht_reg/1000)) +
  #geom_line(aes(color = factor(elevacion))) +
  geom_tile(aes(fill = abs(ddbz), color = abs(ddbz))) +
  scale_fill_viridis(name = "Gradiente \n vertical de \n reflectividad",
                     limits = c(0, 0.06)) +
  scale_color_viridis(name = "Gradiente \n vertical de \n reflectividad",
                      limits = c(0, 0.06)) +
  scale_y_continuous(name = "Altura (km)",
                     limits = c(0, 3),
                     breaks = seq(0, 3, 0.5),
                     expand = c(0,0)) +
  scale_x_datetime(name = NULL,
                   date_breaks = "3 hour",
                   date_labels = "%H:%M",
                   limits = c(as_datetime("2016-01-13 00:00:00"), NA),
                   expand = c(0,0)) +
  theme_minimal()

# 
# dbz_20160123[elevacion == elev[8] & ht_reg > 200] %>%
#   ggplot(aes(date, ht_reg/1000)) +
#   #geom_line(aes(color = factor(elevacion))) +
#   geom_tile(aes(fill = abs(ddbz), color = abs(ddbz))) +
#   scale_fill_viridis(name = "Gradiente \n vertical de \n reflectividad",
#                      limits = c(0, 0.06)) +
#   scale_color_viridis(name = "Gradiente \n vertical de \n reflectividad",
#                       limits = c(0, 0.06)) +
#   scale_y_continuous(name = "Altura (km)",
#                      limits = c(0, 3),
#                      breaks = seq(0, 3, 0.5),
#                     expand = c(0,0)) +
#   scale_x_datetime(name = "Hora (UTC)",
#                    date_breaks = "3 hour",
#                    date_labels = "%H:%M",
#                    limits = c(as_datetime("2016-01-23 00:00:00"), NA),
#                    expand = c(0,0)) +
#   theme_minimal()
# remove(dbz_20160121, dbz_20160123)

```


```{r make-ri, eval=FALSE, include=FALSE}
sup_20160114 <- superficie[day(fecha) == 14]
ri_20160114 <- create.ri(vad_20160114, sup_20160114$fecha, sup_20160114$temp, sup_20160114$presion_estacion, 27.7, 1002.6)
ri_20160114[, caso := "Caso 1"]


sup_20160123 <- superficie[day(fecha) == 23]
ri_20160123 <- create.ri(vad_20160123, sup_20160123$fecha, sup_20160123$temp, sup_20160123$presion_estacion, 34.2, 998.8)
ri_20160123[, caso := "Caso 3"]

ri_vad <- rbindlist(list(ri_20160114, ri_20160123))
ri_vad[, hora := day(date_time)]

remove(sup_20160114, sup_20160123,
            ri_20160114, ri_20160123)
```


```{r estable-vad, eval=FALSE, fig.cap="Series de tiempo de la altura de la capa límite, fig.height=0.24*text.height, fig.ncol=1, cortante vertical y el número de Richarsdon en la capa estable nocturna para todos los casos de estudio. En a) y b) se muestra solo el período donde se observa el LLJ, en c) el período en cada caso se encuentra sombreado. \\label{estable-vad}", fig.subcap=c("Altura de la capa estable \\label{h-vad}", "Cortante ($u_{máx}/z_{máx}$) \\label{cortante-vad}", "Número de Richardson \\label{ri-vad}"), include=FALSE}

ri_vad$hora <- ri_vad$date_time
day(ri_vad$hora) = 14
lim <- as.POSIXct(c(as_datetime("2016-01-14 00:00:00"), as_datetime("2016-01-14 12:00:00")))

ri_vad[hour(hora) %between% c(0, 12)] %>%
  .[(caso == "Caso 1" & hora %between% c(as_datetime("2016-01-14 03:50:00"), as_datetime("2016-01-14 09:40:00"))) |
    (caso == "Caso 2" & hora %between% c(as_datetime("2016-01-14 04:00:00"), as_datetime("2016-01-14 10:50:00"))) |
    (caso == "Caso 3" & hora %between% c(as_datetime("2016-01-14 02:00:00"), as_datetime("2016-01-14 09:30:00")))] %>%
  ggplot(aes(hora, z_max)) +
  geom_line(aes(color = caso)) +
  scale_color_viridis(name = "Casos", discrete = T) +
  scale_y_continuous(name = "h (km)") +
  scale_x_datetime(name = NULL, limits = lim) +
  coord_cartesian(ylim = c(0, 0.8)) +
  theme_minimal()

ri_vad[hour(hora) %between% c(0, 12)] %>%
  .[(caso == "Caso 1" & hora %between% c(as_datetime("2016-01-14 03:50:00"), as_datetime("2016-01-14 09:40:00"))) |
    (caso == "Caso 2" & hora %between% c(as_datetime("2016-01-14 04:00:00"), as_datetime("2016-01-14 10:50:00"))) |
    (caso == "Caso 3" & hora %between% c(as_datetime("2016-01-14 02:00:00"), as_datetime("2016-01-14 09:30:00")))] %>%
  ggplot(aes(hora, u_max/(z_max*1000))) +
  geom_line(aes(color = caso)) +
  scale_color_viridis(name = "Casos", discrete = T) +
  scale_y_continuous(name = expression(paste(u[máx]/z[max], " (1/s)"))) +
  scale_x_datetime(name = NULL, limits = lim) +
  theme_minimal()

ri_vad[hour(hora) %between% c(0, 12)] %>%
  ggplot(aes(hora, ri)) +
  annotate(geom = "rect",
           xmin = as_datetime("2016-01-14 03:50:00"),
           xmax = as_datetime("2016-01-14 09:00:00"),
           ymin = -Inf, ymax = Inf,
           color = "#440154",
           fill = "#440154", alpha = 0.1) +
  annotate(geom = "rect", xmin = as_datetime("2016-01-14 04:00:00"),
           xmax = as_datetime("2016-01-14 09:00:00"),
           ymin = -Inf, ymax = Inf,
           color = "#21908c",
           fill = "#21908c", alpha = 0.1) +
  annotate(geom = "rect", xmin = as_datetime("2016-01-14 02:00:00"),
           xmax = as_datetime("2016-01-14 09:00:00"),
           ymin = -Inf, ymax = Inf,
           color = "#fde725",
           fill = "#fde725", alpha = 0.1) +
  geom_point(aes(color = caso)) +
  scale_color_viridis(name = "Casos", discrete = T) +
  geom_hline(yintercept = 1, color = "darkgray") +
  scale_y_continuous(name = "Ri") +
  scale_x_datetime(name = "Hora UTC", limits = as.POSIXct(c(as_datetime("2016-01-14 00:00:00"), as_datetime("2016-01-14 09:00:00")))) +
  theme_minimal()

remove(gdata, vad_20160121, vad_20160123)
```


##Análisis de las simulaciones con WRF y comparación con observaciones de radar



### Magnitud y dirección del viento

```{r read-WRF-VAD}
# YSU
vad_caso1ysu <- read.vad(paste0(path2, "/caso1_YSU_l/VAD/vad*"))
vad_caso1ysu[, caso := "YSU"]

#MYJ
vad_caso1myj <- read.vad(paste0(path2, "/caso1_MYJ_l/VAD/vad*"))
vad_caso1myj[, caso := "MYJ"]

#ACM2
vad_caso1acm <- read.vad(paste0(path2, "/caso1_ACM2_l/VAD/vad*"))
vad_caso1acm[, caso := "ACM2"]

vad_20160114 <- read.vad(paste0(path2, "20160114/v*"))  
# vad_20160114 <- rbind(subset(sup_vad,
                #             day(date_time) %in% c(13,14)), vad_20160114)
vad_20160114 <- vad_20160114[, caso := "Obs"]
vad_20160114[, rmse3 := NULL]
```



```{r vad-modelo-spd, fig.cap="Magnitud del viento (m/s) estimada a partir de los datos de radar (Obs) y simulada por el modelo WRF utilizando distintos esquemas de CLP para el Caso 1 (14/01/2016) y posteriormente procesados con la técnica VAD. \\label{modelo-spd}", fig.width=0.98*text.width, fig.align='center'}

gdata <- setDT(rbind(vad_20160114, vad_caso1ysu, vad_caso1myj, vad_caso1acm))
gdata[, caso := factor(caso,
                       levels = c("Obs", "YSU", "MYJ", "ACM2"),
                       ordered = T)]
gdata[ht > 0.02 & date_time %between% c(as_datetime("2016-01-13 06:00:00"), as_datetime("2016-01-15 00:00:00")) ] %>%
  ggplot(aes(date_time, ht)) +
  geom_contour(aes(z = spd_smooth, color = ..level..), binwidth = 1) +
  scale_color_viridis(name = "Magnitud\ndel viento", direction = 1,
                      breaks = seq(0, 18, 3), limits = c(0, 19),
                      guide = guide_colorbar(order = 1)) +
  geom_label_contour2(aes(z = spd_smooth, label = ..level.., color = ..level..),
                    size = 4,
                    breaks = seq(0, 18, 1)) +
  scale_x_datetime(name = "Hora (UTC)",
                   date_breaks = "4 hour",
                   date_labels = "%H:%M",
                   limits = c(as_datetime("2016-01-13 06:00:00"), NA),
                   expand = c(0,0)) +
  scale_y_continuous(name = "Altura (km)", limits = c(0,2),
                     expand = c(0,0)) +
  facet_wrap(~caso) +
  theme_minimal() + theme(legend.position = "bottom")

```




```{r vad-modelo-dir, fig.cap="Dirección del viento (grados) estimada por el radar (Obs) y simulada por el modelo WRF utilizando distintos esquemas de CLP para el Caso 1 (14/01/2016) y posteriormente procesados con VAD. \\label{modelo-dir}", fig.width=0.98*text.width, fig.align='center'}

gdata <- setDT(rbind(vad_20160114, vad_caso1ysu, vad_caso1myj, vad_caso1acm))
gdata[, caso := factor(caso,
                       levels = c("Obs", "YSU", "MYJ", "ACM2"),
                       ordered = T)]
gdata[ht > 0.02 & date_time %between% c(as_datetime("2016-01-13 06:00:00"), as_datetime("2016-01-15 00:00:00")) & minute(date_time) == 0 & !is.na(spd_smooth) ] %>%
  ggplot(aes(date_time, ht)) +
  geom_arrow(aes(mag = spd_smooth, angle = di, colour = spd_smooth)) +
  scale_mag() +
  # geom_point(data = subset(vad_20160114, rmse1 > 0.5),
  #            aes(size = rmse1),
  #            shape = 1, color = "grey25") +
  # geom_point(data = subset(vad_20160114, rmse2 > 0.5),
  #            aes(size = rmse2),
  #            shape = 4, color = "grey25") +
  scale_color_viridis(name = "Velocidad\ndel viento",
                      breaks = seq(0, 18, 3), limits = c(0, 19)) +
  scale_size_continuous(range = c(0, 5), guide = "none") +
  scale_y_continuous(name = "Altura (km)", limits = c(0,2)) +
  scale_x_datetime(name = "Hora (UTC)",
                   date_breaks = "4 hour",
                   date_labels = "%H:%M",
        #           limits = c(as_datetime("2016-01-16 06:00:00"), NA),
                   expand = c(0,0)) +
  facet_wrap(~caso) +
  theme_minimal() + theme(legend.position = "bottom")

```


```{r diferencia, fig.cap="Diferencia entre las observaciones y cada simulación para la magnitud del viento (m/s) (a) y el ángulo de la dirección del viento (grados) (b) correspondiente al Caso 1. \\label{dif}", fig.subcap=c("Magnitud del viento (m/s) \\label{dif-spd}", "Ángulo de la dirección del viento (grados) \\label{dif-dir}"), fig.height=0.85*text.height, fig.width=0.48*text.width, fig.ncol=2}

gdata <- setDT(rbind(vad_caso1ysu, vad_caso1myj, vad_caso1acm))

gdata <- gdata[vad_20160114[date_time %between% c(as_datetime("2016-01-13 06:00:00"), as_datetime("2016-01-15 00:00:00")), .(date_time, ht, spd_obs = spd_smooth, di_obs = di, u_obs = u, v_obs = v)],
      on = c("date_time", "ht")] %>%
  .[, dif_spd := spd_obs - spd_smooth] %>%
  .[, di.c := circular(di, units = "degrees", modulo = "pi")] %>%
  .[, di_obs.c := circular(di_obs, units = "degrees", modulo = "pi")] %>%
  .[, dif_di := abs(di_obs.c - di.c)] %>% 
  # .[, dif_di := ifelse(di_obs.c - di.c > 180, di_obs.c - di.c - 360, di_obs.c - di.c)] %>%
  .[, dif_di2 := ifelse(abs(di_obs.c - di.c) > 180, 360 - abs(di_obs.c - di.c), di_obs.c - di.c)] %>% 
  .[, caso := factor(caso,
                       levels = c("Obs", "YSU", "MYJ", "ACM2"),
                       ordered = T)]

gdata[ht > 0.02] %>%
  ggplot(aes(date_time, ht)) +
  geom_contour(aes(z = dif_spd, color = ..level..), binwidth = 1) +
  scale_color_divergent(name = "Magnitud\ndel viento",
                      #breaks = seq(0, 18, 2), limits = c(0, 19),
                      guide = guide_colorbar(order = 1)) +
  scale_x_datetime(name = "Tiempo (UTC)",
                   date_breaks = "4 hour",
                   date_labels = "%H:%M",
                   limits = c(as_datetime("2016-01-14 00:00:00"), NA),
                   expand = c(0,0)) +
  scale_y_continuous(name = "Altura (km)", limits = c(0,2),
                     expand = c(0,0)) +
  facet_wrap(~caso, ncol = 1) +
  theme_minimal() + theme(panel.ontop = T,
                          legend.position="bottom",
                          legend.box = "horizontal")

gdata[ht > 0.02 & caso != "Obs"] %>%
  ggplot(aes(date_time, ht)) +
  geom_tile(aes(fill = abs(dif_di))) +
  scale_fill_divergent(name = "Dirección\ndel viento",
                      #breaks = seq(0, 18, 2), limits = c(0, 19),
                      guide = guide_colorbar(order = 1)) +
  scale_color_divergent(name = "Dirección\ndel viento") +
  scale_x_datetime(name = "Tiempo (UTC)",
                   date_breaks = "4 hour",
                   date_labels = "%H:%M",
                   limits = c(as_datetime("2016-01-13 06:00:00"), NA),
                   expand = c(0,0)) +
  scale_y_continuous(name = "Altura (km)", limits = c(0,2),
                     expand = c(0,0)) +
  facet_wrap(~caso, ncol = 1) +
  theme_minimal() + theme(panel.ontop = T,
                          legend.position="bottom",
                          legend.box = "horizontal")
```




```{r err-spd, fig.cap="Bias, rmse y rmsens en m/s y coeficiente de correlación para la estimación de la velocidad del viento (m/s) con cada simulación en función de la altura y la simulación. \\label{err-spd}", fig.width=0.75*text.width, fig.align='center'}

gdata <- setDT(rbind(vad_caso1ysu, vad_caso1myj, vad_caso1acm)) %>%
  .[vad_20160114[ht != 0.01, .(ht, date_time, obs = spd_smooth)], on = c("ht", "date_time")] %>%
  .[day(date_time) == 14 & ht <= 2.0] %>%
  .[, .(bias = bias.f(spd_smooth, obs),
        rmse = rmse.f(spd_smooth, obs),
        rmsens = rmsens.f(spd_smooth, obs),
        correlación = cor(spd_smooth, obs, use = "complete.obs")), by = .(caso, ht)] %>%
  .[, caso := factor(caso,
                       levels = c("YSU", "MYJ", "ACM2"),
                       ordered = T)] %>%
  melt(id.vars = c("caso", "ht"))

hline <- data.frame(y = 0, variable = c("bias", "correlación"))
ggplot(gdata, aes(ht, value)) +
  geom_hline(data = hline, aes(yintercept = y), color = "darkgray") +
  geom_line(aes(color = caso)) +
  scale_color_viridis(name = "Simulación", discrete = T, option = "viridis") +
  scale_x_continuous(name = "Altura (km)") +
  scale_y_continuous(name = NULL) +
  coord_flip() +
  facet_wrap(~variable, scales = "free") +
  theme_minimal() + theme(legend.position = "bottom")

```

```{r err-tabla}

gdata <- setDT(rbind(vad_caso1ysu, vad_caso1myj, vad_caso1acm)) %>%
  .[vad_20160114[ht != 0.01, .(ht, date_time, obs = spd_smooth)],
    on = c("ht", "date_time")] %>%
  .[day(date_time) == 14 & ht <= 2.0] %>%
  .[, .(bias = bias.f(spd_smooth, obs),
        rmse = rmse.f(spd_smooth, obs),
        rmsens = rmsens.f(spd_smooth, obs),
        correlación = cor(spd_smooth, obs, use = "complete.obs")), by = .(caso)]
err <- gdata

gdata <- setDT(rbind(vad_caso1ysu, vad_caso1myj, vad_caso1acm)) %>%
  .[vad_20160114[ht != 0.01, .(ht, date_time, obs = di)],
    on = c("ht", "date_time")] %>%
  .[day(date_time) == 14 & ht <= 2.0] %>%
  .[, .(di, obs,
        di.c = circular(di, units = "degrees", modulo = "2pi"),
        obs.c = circular(obs, units = "degrees", modulo = "2pi")),
    by = .(caso)] %>%
  .[, .(di, obs, di.c, obs.c,
        dif.di = ifelse(obs.c - di.c > 180, obs.c - di.c - 360, obs.c - di.c)),
    by = .(caso)] %>%
  .[, .(bias = bias.c(dif.di),
        rmse = rmse.c(dif.di),
        rmsens = rmsens.c(dif.di),
        correlación = cor.circular(di.c, obs.c)), by = .(caso)]

err <- cbind(err, gdata)
err[,6] <- NULL

kable(err, format = "latex",
      digits = 3,
      booktabs = T,
      caption = "Comparación entre las simulaciones y las observaciones de radar a partir de distintos errores. El bias, rmse, rmsens se expresan en m/s. \\label{err}") %>%
  add_header_above(c(" ", "Velocidad" = 4, "Dirección" = 4)) #%>%
  #kable_styling(latex_options = "hold_position")
```



```{r perfiles-mod, fig.cap="Perfil de viento (m/s) observado por el radar a las 06 y las 17 UTC y perfiles simulados por el modelo para los mismos momentos. Las marcas en los ejes indican la magnitud del viento máxima y mínima y la altura a la que ocurren. \\label{perfil-mod}", fig.width=0.95*text.width, fig.align='center'}

gdata <- setDT(rbind(vad_20160114, vad_caso1ysu, vad_caso1myj, vad_caso1acm))
gdata[, caso := factor(caso,
                       levels = c("Obs", "YSU", "MYJ", "ACM2"),
                       ordered = T)] %>%
  .[, hora := hour(date_time)] %>%
  .[minute(date_time) == 00 & day(date_time) == 14 & hour(date_time) %in% c(07, 17) & ht < 2.5 &
      !is.na(spd_smooth)] %>%
  ggplot(aes(ht, spd_smooth, color = caso)) +
  geom_line() +
  geom_rug(data = gdata[minute(date_time) == 00 & hour(date_time) == 6][, maxspd := max(spd_smooth, na.rm = T), by = caso][spd_smooth == maxspd]) +
  geom_rug(data = gdata[minute(date_time) == 00 & hour(date_time) == 6 & ht > 0.5][, minspd := min(spd_smooth, na.rm = T), by = caso][spd_smooth == minspd]) +
  # geom_ribbon(aes(ymin = spd_smooth - rmse2, ymax = spd_smooth + rmse2,
  #             fill = as.factor(hour(date_time))),
  #             alpha = 0.5, color = NA) +
  coord_flip() +
  scale_color_manual(name= NULL, values = c("#B63679FF", viridis_pal()(3))) +
  scale_y_continuous(name = "V (m/s)") +
  scale_x_continuous(name = "Altura (km)", breaks = seq(0, 2.5, 0.5),
                     limits = c(0, 2.5)) +
  facet_wrap(~hora, labeller = labeller(hora = c("6" = "06 UTC", "17" = "17 UTC"))) +
  theme_minimal()
```




```{r hodografa-wrf, fig.cap="Hodógrafa temporal para tres niveles. Cada círculo representa un valor horario (con circulos más grandes cada 4 horas) y el cuadrado marca el primer tiempo (00 UTC). \\label{hodografa-mod}", fig.width=0.95*text.width, fig.align='center'}

gdata <- rbind(vad_20160114, vad_caso1ysu, vad_caso1myj, vad_caso1acm)
gdata <- as.data.table(gdata) %>%
  .[, hora := hour(date_time)] %>%
  .[minute(date_time) == 00 & day(date_time) == 14 & hora < 13] %>%
  .[, caso2 := factor(caso,
                       levels = c("Obs", "YSU", "MYJ", "ACM2"),
                       ordered = T)]

gdata[ht %in% c(0.3, 0.5, 1.0) & !is.na(spd_smooth)] %>%
  ggplot(aes(u, v,  color = caso2)) +
  geom_hline(yintercept = 0, color = "darkgrey") +
  geom_vline(xintercept = 0, color = "darkgrey") +
  geom_point(aes(x = ifelse(hour(date_time) != 0, u, NA)), size = 1) +
  geom_point(aes(x = ifelse(hour(date_time) %in% c(0,4,8,12), u, NA)),
             size = 2) +
  geom_point(aes(x = ifelse(hour(date_time) == 0, u, NA)), shape = 15,
             size = 3) +
  geom_path() +
  # geom_text_repel(aes(label = JumpBy(hora, 6, fill = NA)),
  #                  data = gdata[ht %in% c(0.3, 0.5, 1.0)]) +
  scale_color_manual(name="Altura", values = c("#B63679FF", viridis_pal()(3))) +
  scale_x_continuous(name = "u (m/s)") +
  scale_y_continuous(name = "v (m/s)") +
  coord_equal() +
  facet_wrap(~ht) +
  theme_minimal()

```



```{r leo-pbl}

caso.YSU <- ReadNetCDF(paste(path2,"caso1_YSU_l/spd_YSU.nc", sep = "")) %>%
  mutate(exchh = ReadNetCDF(paste(path2,"caso1_YSU_l/exchh_YSU.nc", sep = ""), out = "vector")[[1]],
         pblh = ReadNetCDF(paste(path2,"caso1_YSU_l/pblh_YSU.nc", sep = ""), out = "vector")[[1]],
         ust = ReadNetCDF(paste(path2,"caso1_YSU_l/ust_YSU.nc", sep = ""), out = "vector")[[1]],
         L = ReadNetCDF(paste(path2,"caso1_YSU_l/l_YSU.nc", sep = ""), out = "vector")[[1]],
         param = "YSU") %>%
  .[, lev := lev*1000 - 73] %>%
  .[, c("pblh", "ust", "L") := .(pblh[1], ust[1], L[1]), by = .(time, lon, lat, param)] %>%
  .[, regimen := ifelse(L <= 0, "Inestable", "Estable")] %>%
  .[time %between% as.POSIXct(c("2016-01-13 22:10:00", "2016-01-14 22:00:00"), tz = "UTC"), ] %>%
  .[inside(lon, lat) == T] %>%
  .[lev > -25,]

caso.MYJ <- ReadNetCDF(paste(path2,"caso1_MYJ_l/spd_MYJ.nc", sep = "")) %>%
  mutate(exchh = ReadNetCDF(paste(path2,"caso1_MYJ_l/exchh_MYJ.nc", sep = ""), out = "vector")[[1]],
         pblh = ReadNetCDF(paste(path2,"caso1_MYJ_l/pblh_MYJ.nc", sep = ""), out = "vector")[[1]],
         ust = ReadNetCDF(paste(path2,"caso1_MYJ_l/ust_MYJ.nc", sep = ""), out = "vector")[[1]],
         L = ReadNetCDF(paste(path2,"caso1_MYJ_l/l_MYJ.nc", sep = ""), out = "vector")[[1]],
         param = "MYJ") %>%
  .[, lev := lev*1000 - 73] %>%
  .[, c("pblh", "ust", "L") := .(pblh[1], ust[1], L[1]), by = .(time, lon, lat, param)] %>%
  .[, regimen := ifelse(L <= 0, "Inestable", "Estable")] %>%
  .[time %between% as.POSIXct(c("2016-01-13 22:10:00", "2016-01-14 22:00:00"), tz = "UTC"), ] %>%
  .[inside(lon, lat) == T] %>%
  .[lev > -25,]

caso.ACM2 <- ReadNetCDF(paste(path2,"caso1_ACM2_l/spd_ACM2.nc", sep = "")) %>%
  mutate(exchh = ReadNetCDF(paste(path2,"caso1_ACM2_l/exchh_ACM2.nc", sep = ""), out = "vector")[[1]],
         pblh = ReadNetCDF(paste(path2,"caso1_ACM2_l/pblh_ACM2.nc", sep = ""), out = "vector")[[1]],
         ust = ReadNetCDF(paste(path2,"caso1_ACM2_l/ust_ACM2.nc", sep = ""), out = "vector")[[1]],
         L = ReadNetCDF(paste(path2,"caso1_YSU_l/l_YSU.nc", sep = ""), out = "vector")[[1]],
         param = "ACM2") %>%
  .[, lev := lev*1000 - 73] %>%
  .[, c("pblh", "ust", "L") := .(pblh[1], ust[1], L[1]), by = .(time, lon, lat, param)] %>%
  .[, regimen := ifelse(L <= 0, "Inestable", "Estable")] %>%
  .[time %between% as.POSIXct(c("2016-01-13 22:10:00", "2016-01-14 22:00:00"), tz = "UTC"), ] %>%
  .[inside(lon, lat) == T] %>%
  .[lev > -25,]

all.pbl <- rbind(caso.YSU, caso.MYJ, caso.ACM2) %>%
  .[lat %~% -31.8484 & lon %~% -60.5372] %>%
  .[, param :=  factor(param,
                       levels = c("YSU", "MYJ", "ACM2"),
                       ordered = T)]

#saveRDS(all.pbl[lev == 25, .(pblh, date, param)], "pblh")

remove(list = c("caso.YSU", "caso.MYJ", "caso.ACM2"))
```




```{r L-parm, fig.cap="Longitud de Monin Obukhov (m) en función del tiempo, para cada simulación. Los puntos violetas corresponden al régimen estable (nocturno) y los puntos rosas corresponden al régimen inestable (diurno) \\label{L-param}", fig.width=0.95*text.width, fig.align='center'}

ggplot(all.pbl, aes(time, L)) +
  geom_point(aes(color = regimen)) +
  geom_hline(yintercept = 0, color = "darkgrey") +
  scale_color_manual(name = "Regimen", values = color_manual) +
  scale_y_continuous(name = "L (m)", breaks = seq(-400, 300, 50)) +
  scale_x_datetime(name = "Hora (UTC)",
                   date_breaks = "6 hours",
                   date_labels = "%H") +
  facet_wrap(~param) +
  theme_minimal()

```


#### Altura de la capa límite


```{r pblh-wrf, fig.cap="Altura de la capa límite (m) en cada simulación. \\label{pblh-wrf}", fig.subcap=c("Estimada directamente por cada esquema de CLP. \\label{pblh}", "Comparación entre la altura calculada por cada esquema (línea) y la estimada a partir de la altura del viento máximo (puntos) sólo en el período estable. \\label{pblh-spd}"), fig.width=0.75*text.width, fig.height=0.35*text.height, fig.align='center', fig.ncol=1}

all.pbl[lev < 30] %>%
  ggplot(aes(time, pblh)) +
  geom_vline(xintercept = as_datetime("2016-01-14 09:40:00"),
             color = "darkgray") +
  geom_line(aes(color = param), linetype = 1) +
  scale_color_viridis(name = "Simulación", discrete = T, option = "viridis") +
  scale_y_continuous(name = "Altura de la capa límite (m)", limits = c(0, 3000)) +
  scale_x_datetime(name = "Hora UTC",
                   date_breaks = "4 hours",
                   date_labels = "%H") +
  theme_minimal()

all.pbl[lev < 2500 & L >=0 , .(pblh = pblh[1], pblh.spd = lev[which.max(spd)], L = L[1]), by = .(time, param)] %>%   
  # .[!is.na(pblh), ] %>%
  ggplot(aes(time, pblh)) +
  # geom_vline(xintercept = as_datetime("2016-01-14 09:40:00"),
  #            color = "darkgray") +
  geom_line(aes(color = param), linetype = 1) +
  geom_point(aes(y = pblh.spd, color = param)) +
  scale_color_viridis(name = "Simulación", discrete = T, option = "viridis") +
  scale_y_continuous(name = "Altura de la capa límite (m)") +
  scale_x_datetime(name = "Hora UTC",
                   date_breaks = "3 hours",
                   date_labels = "%H",
                   limits = c(as_datetime("2016-01-14 00:00:00"), NA),
                   expand = c(0,0)) +
   coord_cartesian(ylim = c(0, 600)) +
  facet_wrap(~param, ncol = 1) +
  theme_minimal()

```



```{r dbz-wrf, fig.cap="Valor absoluto del gradiente vertical de reflectividad (dBZ/m) en función de la altura y el tiempo para el Caso 1 y la altura de la capa límite estimada en cada simulación. \\label{dbz-wrf}", fig.align='center',  fig.height=0.4*text.height}
elev <- unique(dbz_20160114$elevacion)
pbl <- readRDS("pblh")
dbz_20160114[elevacion == elev[8] & ht_reg > 200] %>%
  ggplot(aes(date, ht_reg/1000)) +
  geom_tile(aes(fill = abs(ddbz), color = abs(ddbz))) +
  scale_fill_viridis(name = "Gradiente \n vertical de \n reflectividad",
                     limits = c(0, 0.06)) +
  scale_color_viridis(name = "Gradiente \n vertical de \n reflectividad",
                      limits = c(0, 0.06)) +
  scale_y_continuous(name = "Altura (km)", limits = c(0, 3)) +
  scale_x_datetime(name = "Hora (UTC)",
                   date_breaks = "3 hour",
                   date_labels = "%H:%M",
                   limits = c(as_datetime("2016-01-14 00:00:00"), NA),
                   expand = c(0,0)) +
  geom_point(data = pbl, aes(date, pblh/1000, shape = param), size = 1) +
  scale_shape_discrete(name = "Simulación") +
  theme_minimal()
remove(files, dbz_20160114)
```


#### Coeficientes de difusividad turbulenta

```{r make-ulke}
all.pbl <- all.pbl[, c("kh.u", "km.u", "u.u") := .(
  kh.ulke(lev, pblh, L, ust),
  km.ulke(lev, pblh, L, ust),
  u.ulke(lev, pblh, L, ust))] %>%
  .[, Pr := km.u/kh.u]
```


```{r pr, fig.cap="Variación del número de Prandtl calculado a partir del modelo propuesto por Ulke 2000 con las variables de cada simulación y promediado en cada periodo. \\label{Pr}", fig.align='center', fig.width=0.95*text.width}
all.pbl_norm <- all.pbl[, `:=`(kh.u_norm = kh.u/(ust*0.4*pblh),
             km.u_norm = km.u/(ust*0.4*pblh),
             lev_norm = lev/pblh),
             by = .(param, regimen)] %>%
  .[, .(lev_norm = seq(0, 1, by = 0.1),
        kh.u_norm = approx(lev_norm, kh.u_norm, xout = seq(0, 1, by = 0.1))$y,
        km.u_norm = approx(lev_norm, km.u_norm, xout = seq(0, 1, by = 0.1))$y),
    by = .(param, regimen, time)] %>%
  .[, lapply(.SD, mean, na.rm = T), by = .(param, lev_norm, regimen), .SDcols = -"time"]

group_by(all.pbl, param, lev, regimen) %>%
  summarise(Pr = mean(Pr, na.rm = T)) %>%
ungroup() %>%
ggplot(aes(lev, Pr)) +
  geom_line(aes(color = as.factor(param))) +
  scale_color_viridis(name = "Esquema",discrete = T, option = "viridis",
                       labels=c(expression(U2000[YSU]),
                               expression(U2000[MYJ]),
                               expression(U2000[ACM2]))) +
  scale_y_continuous(name = "Km/Kh", expand = c(0,0)) +
  scale_x_continuous(name = "z(m)", limits = c(0,1500)) +
  facet_wrap(~regimen, scales = "free") +
  coord_flip() +
  theme_minimal()
```

```{r tabla-clp}
hL <- group_by(all.pbl, param, regimen) %>%
  summarise(h_mean = mean(pblh, na.rm = T),
            L_mean = mean(L, na.rm = T),
            ust_mean = mean(ust, na.rm = T),
            Pr_mean =  mean(Pr, na.rm = T)) %>%
  .[, hL := h_mean/L_mean]

names(hL) <-  c("Simulación", "Regimen", "$\\overline{h}$", "$\\overline{L}$", "$\\overline{u*}$", "$\\overline{Pr}$", "$h/L$")

names(hL)[3] <- paste0(names(hL)[3], footnote_marker_number(1, "latex"))
names(hL)[4] <- paste0(names(hL)[4], footnote_marker_number(2, "latex"))
names(hL)[5] <- paste0(names(hL)[5], footnote_marker_number(3, "latex"))
names(hL)[6] <- paste0(names(hL)[6], footnote_marker_number(4, "latex"))

kable(hL, "latex",
      caption = "Parámetros característicos de la capa límite para cada simulación y regimen, promediados para todo el periodo y todo el perfil (en los casos que corresponda). \\label{tabla-clp}",
      escape = F,
      booktabs = T,
      digits = c(0,0,2,2,4,2,2)) %>%
  kable_styling(full_width = F) %>%
  footnote(general_title = "Nota",
           escape = F,
           number = c("Altura de la CLP promediada.",
                      "Longitud de Monin Obukhov promediada.",
                      "Velocidad de fricción promediada.",
                      "Número de Prandtl promediado.")) # %>%
  #kable_styling(latex_options = "hold_position")
```





```{r k_ulke_wrf, fig.cap="Coeficientes de difusividad turbulenta de calor sensible (a) y cantidad de movimiento (b) promediados entre las 05 y 06 UTC (período estable, izquierda) y entre las 16 y 17 UTC (período inestable, derecha) de la capa límite en todas las simulaciones.  \\label{k-ulke-wrf}", fig.subcap=c("Calor $K_h$ ($m^2/s$). \\label{kh-wrf}", "Moviento $K_m$ ($m^2/s$). \\label{km-wrf}"), fig.align='center', fig.width=0.98*text.width, fig.ncol=1, fig.height=0.40*text.height}

all.pbl <- all.pbl[, exchm := Pr*exchh]

# ggplot(all.pbl[regimen == "Estable"], aes(lev, exchh, group = factor(lev))) +
#   geom_boxplot() +
#   facet_wrap(~param)

d <- all.pbl[time %between% c(as_datetime("2016-01-14 04:00:00"), as_datetime("2016-01-14 05:00:00")) | time %between% c(as_datetime("2016-01-14 16:00:00"), as_datetime("2016-01-14 17:00:00"))] %>%
  group_by(param, lev, regimen) %>%
  summarise(Kh.m = median(exchh, na.rm = T), Km.m = median(exchm, na.rm = T)) %>%
  ungroup()

ggplot(all.pbl[time %between% c(as_datetime("2016-01-14 04:00:00"), as_datetime("2016-01-14 07:00:00"))], aes(lev, exchh)) +
  geom_line(aes(color = as.factor(param))) +
  scale_color_viridis(name = "Esquema",discrete = T, option = "viridis") +
  scale_y_continuous(name = expression(paste(K[h], " (", m^2,s^{-1}, ")"))) +
  scale_x_continuous(name = "Altura sobre el nivel del suelo (Km)",
                     limits = c(0, 500)) +
  facet_wrap(~time, scales = "free") +
  coord_flip() +
  theme_minimal()

ggplot(d, aes(lev, Kh.m)) +
  geom_line(aes(color = as.factor(param))) +
  scale_color_viridis(name = "Esquema",discrete = T, option = "viridis") +
  scale_y_continuous(name = expression(paste(K[h], " (", m^2,s^{-1}, ")"))) +
  scale_x_continuous(name = "Altura sobre el nivel del suelo (km)",
                     limits = c(0, 2500)) +
  facet_wrap(~regimen, scales = "free") +
  coord_flip() +
  theme_minimal()

ggplot(d, aes(lev, Km.m)) +
  geom_line(aes(color = as.factor(param))) +
  scale_color_viridis(name = "Esquema",discrete = T, option = "viridis") +
  scale_y_continuous(name = expression(paste(K[m], " (", m^2,s^{-1}, ")"))) +
  scale_x_continuous(name = "Altura sobre el nivel del suelo (km)",
                     limits = c(0, 2500)) +
  facet_wrap(~regimen, scales = "free") +
  #labs(title = "Perfiles a partir del promedio del dominio") +
  coord_flip() +
  theme_minimal()

remove(d)
```

