---
title: "Agradecimientos"
date: ''
output:
  pdf_document:
    keep_tex: yes
    latex_engine: xelatex
    number_sections: yes
    toc: yes
    toc_depth: 4
classoption: oneside
documentclass: book
fontsize: 12pt
geometry: inner = 2cm, outer = 2cm, top = 2.5cm, bottom = 2.5cm
header-includes:
- \linespread{1.25}
- \usepackage{subfig}
- \usepackage{hyperref}
- \usepackage[textsize=tiny]{todonotes}
lang: es-AR
link-citation: yes
csl: Bibliografia/meteorologica.csl
---

En primer lugar quiero agradecer a las personas que desarrollaron y pusieron a disposición librerías, códigos e información libre para que esta tesis llegara a buen puerto. A J. Helmus y S. Collis sin los cuales seguiría lidiando con el aliasing, a M. Dixon por hacer que lo datos de radar sean entendibles por humanos, a Rosanna van Hespen cuyo blog salvó a esta tesis de ser escrita en word, a la comunidad de R-Ladies por el apoyo y los concejos, hacen que el camino sea menos empinado. Y a la decena de personas que desarrollaron las incontables librerías de R que dieron forma y color a esto, en especial a Elio Campitelli que viene allanando el camino a todo meteorólogo que se anime a incursionar en el mundo de R. 

Al Dr. Ramón de Elía por su tiempo y concejos cuando recién comenzaba a dar los primeros pasos y al Dr. Lluis Fita Borrell por ayudarme a desentrañar los misterios del WRF y fortran. 

A la comunidad del DCAO y CIMA por abrirme sus puertas y acompañarme todos estos años de horas y días interminables en la facu. En especial a los docentes por su dedicación y amabilidad, espero haber estado a la altura de todo el esfuerzo que hacen día a día.

A Juan y Marisa por guiarme en este sinuoso camino que es hacer una tesis de licenciatura. Por la paciencia y confianza aún cuando el trabajo y las materias me desbordaban y la tesis quedaba en otro plano. Me enseñaron muchísimas cosas y me contagiaron su entusiasmo y ganas de ir más allá, gracias!

A Expedición Ciencia por invitarme a la aventura de ponerme en los zapatos de un científico, preguntarme y descubrir el mundo. Me ayudan a crecer y desafiarme con cada proyecto. Gracias por permitirme aprender y crecer todos los días, por las oportunidades y el apoyo. Son el sueño hecho realidad de una (falsa) cordobesa que ahora va por el mundo intentando contagiar la curiosidad por descubrir. 

A mi gran familia por todo. Por acompañarme en cada momento, y apoyarme en cada locura. Por estar ahí, lejos pero siempre presentes. Por todo el amor y la paciencia que me tienen. Porque lo que soy es gracias a ustedes.

Y finalmente a mi pequeña familia, a Elio. Un compañero de clases que se convirtió en el compañero de mi vida. Gracias por acompañarme en el camino, por el amor y las risas, por apoyarme y ayudarme a ser mejor cada día.





