---
title: "Prueba dBZ"
author: "Paola Corrales"
date: "January 15, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      cache = TRUE)

# librerías
library(metR)
library(ggplot2)
library(ggforce)
library(lubridate)
library(magrittr)
library(dplyr)
library(dtplyr)
library(viridis)
library(directlabels)
library(data.table)
library(patchwork)
library(ncdf4)
#source("geom_contourlabel.R")
source("helpfun.R")
```

```{r}
ReadRadar <- function(file) {
  radar <- nc_open(file)
  azimut <- ncvar_get(radar, 'azimuth')   
  elevacion <- ncvar_get(radar, 'elevation') 
  rango <- ncvar_get(radar, 'range')      
  # V <- ncvar_get(radar, 'V')            
  # Vda <- ncvar_get(radar, 'Vda')
  dbz <- ncvar_get(radar, 'dBZ')
  # Vda[Vda > 99999] <- NA
  datetime <- radar$dim$time$units %>% 
    strsplit(., "since") %>% 
    .[[1]] %>% 
    .[2] %>% 
    ymd_hms(tz = "UTC")
  second(datetime) <- 0
  dimnames(dbz) <- list(rango = rango, azimut = azimut)
  radar <- setDT(melt(dbz, value.name = "dbz")) 
  radar[, date := datetime]
  
  radar[, elevacion := elevacion, by = rango]
  R <- 6371.0*1000 #km
  Rp <- 4*R/3
  radar[, ht := sqrt((rango^2)+(Rp^2)+2*rango*Rp*sin(pi*elevacion/180))-Rp ]
  radar[elevacion < 6 & ht < 5000]
  
  
  ht_reg <- seq(0, 5000, by = 50)
  radar[, NNa := sum(!is.na(dbz)), by = .(azimut, elevacion, date)]
  reg <- radar[NNa > 3, .(ht_reg = ht_reg,
                 dbz_reg = approx(ht, dbz, xout = ht_reg)$y), 
        by = .(azimut, elevacion, date)] %>% 
  .[elevacion < 6, .(dbz = mean(dbz_reg, na.rm = T)), 
    by = .(ht_reg, date, elevacion)] 
  reg[, ddbz := metR:::.derv(dbz, ht_reg), by = .(elevacion, date)]
  reg
}

files <- Sys.glob("~/Radar/VAD/PARANA/20160114/240/*.nc")
radar <- rbindlist(lapply(files, ReadRadar))

files <- Sys.glob("~/Radar/VAD/PARANA/20160114/Prueba/*.nc")
radar2 <- rbindlist(lapply(files, ReadRadar))
rad <- rbind(radar, radar2)

# radar[elevacion == elev[3] & !is.na(dbz), ] %>%
#   RepeatLon(., colname = "azimut") %>% 
#   ggplot(aes(azimut, rango/1000)) + 
#   geom_path(data = map[rango <= 300*1000], aes(group = group), color = "darkgray") +
#   geom_point(aes(color = dbz, size = rango)) +
#   #scale_color_divergent() +
#   scale_size_area(max_size = 0.1) +
#   scale_x_continuous(name = NULL, labels = NULL, breaks = seq(0, 359, 90)) +
#   scale_y_continuous(name = "Distancia al centro (Km)", breaks = c(40, 120, 180, 240), 
#                      limits = c(0, 300), expand = c(0, 0)) + 
#   guides(size = "none") +
#   coord_polar() +
#   theme_minimal() + theme(legend.position = "bottom") +
#   facet_wrap(~date)
```

```{r}
radar_n <-  radar[, .(ht_norm = seq(0, 3000, by = 10),
                      dbz_norm = approx(ht, dbz, xout = seq(0, 3000, by = 10))$y), 
                  by = .(elevacion, date)]

radar[, ddbz := metR:::.derv(dbz, ht_reg), by = .(elevacion, date)]
```


```{r dbz1, fig.cap="Variación de dBZ con la altura a lo largo de un día (14/01/2016) para distintos ángulos de elevación. La línea negra corresponde a -5 dBZ"}
ggplot(radar, aes(date, ht_reg)) +
  geom_contour(aes(z = ddbz, color = ..level..)) +
  # geom_contour(aes(z = dbz), breaks = -5, color = "black") +
  scale_color_viridis(name = "dBZ") +
  scale_y_continuous(limits = c(0, 3000)) +
  facet_wrap(~elevacion) +
  theme_minimal()
```


```{r dbz2, fig.cap="Idem gráfico anterior pero solo para 5 grados y geom_tile (similar a los contornos pero rellena cada pixel con el valor de la variable)."}
elev <- unique(radar$elevacion)
radar[elevacion == elev[8]] %>%
ggplot(aes(date, ht_reg)) +
  #geom_line(aes(color = factor(elevacion))) +
  geom_tile(aes(fill = ddbz)) +
  scale_fill_viridis(name = "dBZ", limits = c(-0.001, 0.001)) +
  scale_y_continuous(limits = c(0, 3000)) +
  facet_wrap(~elevacion) +
  theme_minimal()
    
```

```{r dbz3, fig.cap="Agrego en negro la estimación de la altura de la capa límite hecha por cada esquema."}
elev <- unique(radar$elevacion)
all.pbl <- readRDS("pblh")

dbz_radar[elevacion == elev[8]] %>% 
  ggplot(aes(date, ht_reg)) +
  #geom_line(aes(color = factor(elevacion))) +
  geom_contour_fill(aes(z = abs(ddbz)), binwidth = 0.01) +
  scale_fill_viridis(name = "dBZ", limits = c(0, 0.06)) +
  #geom_point(data=all.pbl, aes(date, pblh, shape = param)) +
  scale_y_continuous(limits = c(200, 3000)) +
  theme_minimal()
    
```




```{r dbz4, fig.cap="Agrego algunos tiempos previos y posteriores."}


ggplot(rad[elevacion == elev[8]], aes(date, ht_reg)) +
  geom_contour(aes(z = dbz, color = ..level..)) +
  scale_color_viridis(name = "dBZ") +
  #geom_point(data=all.pbl[lev == 25], aes(date, pblh, shape = param)) +
  scale_y_continuous(limits = c(0, 3000)) +
  theme_minimal()
```

